softwareone-platform/ffc-finops-operations

- .github/workflows/pr-build-merge.yaml
- app/collections.py
- app/main.py
- app/models.py
- pyproject.toml
- tests/test_entitlements_api.py
- uv.lock
> chore: Fix issues flagged by SonarCloud to please our AI overlords

- app/db/__init__.py
- app/db/db.py
- app/db/handlers.py
- tests/conftest.py
- tests/db/test_transactions.py
- tests/utils.py
> MPT-5773 Transaction management

- app/routers/accounts.py
- tests/test_accounts_api.py
- tests/test_auth.py
Improve new code's test coverage
> Mpt 6965 improve accounts test coverage

- app/auth/constants.py
- app/db/handlers.py
- app/routers/entitlements.py
- app/routers/organizations.py
- tests/test_accounts_api.py
- tests/test_auth.py
- tests/test_datasources_api.py
- tests/test_employees_api.py
- tests/test_entitlements_api.py
- tests/test_organizations_api.py
- tests/test_systems_api.py
It's the simple things in life that make us happy :)
> chore: Add missing fullstops to error responses

- app/routers/accounts.py
- app/routers/users.py
- tests/commands/test_check_expired_invitation.py
- tests/commands/test_create_operations_account.py
- tests/commands/test_invite_user.py
- tests/commands/test_redeem_entitlements.py
- tests/conftest.py
- tests/test_users_api.py
Add GET /users/{id}
Adjust commands test 
Add Test for /users/{id}
> Mpt 6623 user get details

- app/auth/login.py
- app/db/handlers.py
- app/db/models.py
- app/pagination.py
- app/routers/accounts.py
- app/routers/entitlements.py
- app/routers/organizations.py
- app/routers/systems.py
- app/routers/users.py
- app/schemas/core.py
- app/schemas/users.py
- tests/test_schemas.py
- tests/test_users_api.py
Add /users Endpoints and related logic. 
Refactor of from_orm and to_orm
> Add /users Endpoints and related logic.

- app/routers/users.py
- tests/test_users_api.py
> Add POST /users/{id}/disable

- app/db/handlers.py
- app/routers/users.py
- tests/api/users/test_collection.py
> Add DELETE /users/{id}

- app/routers/users.py
- tests/api/users/test_collection.py
> Mpt 6523 user enable endpoint

- app/auth/auth.py
- app/routers/accounts.py
Small refactor of get authentication context
> Mpt 7341 get authentication context

- app/db/handlers.py
- app/pagination.py
- app/routers/users.py
- app/schemas/employees.py
- tests/api/test_accounts_api.py
- tests/db/test_handlers.py
Refactor of Delete user by id
Increase `le` to LimitOffsetParams in pagination.py
Add modelConfig in EmployeeBase
> Refactor of Delete user by id

- app/commands/openapi.py
- app/main.py
- app/openapi.py
- tests/commands/test_openapi.py
- tests/test_openapi.py
- uv.lock
> MPT-7967 customize openapi generation to include RQL docs

- app/routers/organizations.py
- app/rql.py
- tests/api/test_organizations_api.py
Add RQL to Organization Model.
FIX bug when filtering by datetime
> Add RQL to Organization Model.

- app/api_clients/azure.py
- app/blob_storage.py
- app/dependencies/path.py
- app/routers/chargesfiles.py
- app/rql.py
- tests/api/charges_file/test_chages_file.py
- tests/azure_blob_storage/test_azure_upload.py
Add GET `/charges/{id}/download` to receive the charge file zip file to download
Improve tests
> Mpt 7550 billing download charges file endpoint

- app/routers/chargesfiles.py
- app/schemas/charges.py
- tests/api/charges_file/test_chages_file.py
- tests/azure_blob_storage/test_azure_upload.py
- uv.lock
Add GET `/charges/{id}` to download a given charge file by id
> Mpt 7553 billing get charges file detail endpoint

- .dockerignore
- .gitignore
Adding few more exclusions to .dockerignore. It should further reduce docker build time, especially in local environment of developers.
Also, added .idea dir to .gitignore.
> Add to ignore files.

- app/templates/emails/invitation.html.j2
{{text.user_name}}
{{text.expire_date}}
{{links.portal_link}}
{{email.support}}
> added invitation.html.j2 mail templates

- app/dependencies/db.py
- app/main.py
- app/routers/expenses.py
- app/rql.py
- app/schemas/expenses.py
- tests/api/test_expenses_api.py
[MPT-10785] Add GET /v1/expenses endpoint to return a list of expenses
[MPT-10785]: https://softwareone.atlassian.net/browse/MPT-10785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MPT-10785] Add GET /v1/expenses endpoint to return a list of expenses

- app/commands/calculate_accounts_stats.py
- app/commands/check_expired_invitations.py
- app/commands/cleanup_obsolete_datasource_expenses.py
- app/commands/fetch_datasource_expenses.py
- app/commands/redeem_entitlements.py
- app/commands/serve.py
- app/conf.py
- app/telemetry.py
- docker-compose.yaml
- tests/conftest.py
- tests/test_telemetry.py
Backport https://github.com/softwareone-platform/ffc-finops-operations/pull/215 to v4
> [BACKPORT] Fix SQLAlchemy OTEL issues (MPT-11422 )

- app/rql.py
- tests/api/test_expenses_api.py
- tests/api/test_organizations_api.py
- uv.lock
https://softwareone.atlassian.net/browse/MPT-13377
> feat: Add missing RQL filters for Organizations and Datasource Expenses (MPT-13377)

- app/rql.py
- tests/api/test_expenses_api.py
- tests/api/test_organizations_api.py
- uv.lock
https://softwareone.atlassian.net/browse/MPT-13377
> [BACKPORT] feat: Add missing RQL filters for Organizations and Datasource Expenses (MPT-13377)
